learning_users/basic_app/urls.py
from django.conf.urls import url
from basic_app import views

# App name
app_name = "basic_app"



urlpatterns = [
    url(r'^register/$', views.register, name="register"),
    url(r'^user_login/$', views.user_login, name="user_login"),
    
]

learning_users/learning_users/urls.py
from django.contrib import admin
from django.conf.urls import url, include
from django.urls import path
from basic_app import views

urlpatterns = [
    url(r'^$', views.index, name="index"),
    path('admin/', admin.site.urls),
    url(r'^basic_app/', include("basic_app.urls")),
    url(r'^logout/$', views.user_logout, name='logout'),
]

learning_users/basic_app/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class UserInfo(models.Model):

    user = models.OneToOneField(User, on_delete=models.CASCADE)

    portfolio = models.URLField(blank=True)
    picture = models.ImageField(upload_to='profile_pics', blank=True)
    
    def __str__(self):
        return self.user.username
    
    

learning_users/basic_app/forms.py
from django import forms
from django.contrib.auth.models import User
from basic_app.models import UserInfo

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username', 'email', 'password',)


class UserInfoForm(forms.ModelForm):
    class Meta:
        model = UserInfo
        fields = ('portfolio', 'picture')

learning_users/basic_app/views.py
from django.shortcuts import render
from .forms import UserForm, UserInfoForm
from .models import UserInfo


from django.contrib.auth import login, logout, authenticate
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required


# Create your views here.

def index(request):
    return render(request, "basic_app/index.html")

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse("index"))

def register(request):
    
    registered = False

    if request.method == "POST":

        user_form = UserForm(data=request.POST)
        profile_form = UserInfoForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():

            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            if 'picture' in request.FILES:
                profile.picture = request.FILES['picture']
            
            profile.save()

            registered = True
        else:
            print(user_form.errors, profile_form.errors)

    else:
        user_form = UserForm()
        profile_form = UserInfoForm()
    
    return render(request, 'basic_app/registration.html', 
                            {'user_form':user_form,
                             'profile_form':profile_form,
                             'registered':registered})
                             

def user_login(request):

    if request.method == "POST":

        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)

        if user is not None:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('index'))

            else:
                return HttpResponseRedirect("Account not Active!")

        else:
            print("Username and Password incorrect!")
            return HttpResponseRedirect(reverse("basic_app:user_login"))

    else:
        return render(request, "basic_app/login.html")

learning_users/templates/basic_app/base.html
{% load static %}
<!DOCTYPE html>

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Base Directory</title>
    <!-- Bootstrap -->
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
    <!-- BOOTY JS -->
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
    <!-- css -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">

</head>
<body>

    <nav class="navbar navbar-expand-md navbar-primary bg-warning">
        <div class="container">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item"><a href="{%url 'index' %}" class="navbar-brand"><b>DJANGO</b></a></li>
                
                
                {% if user.is_authenticated %}
                
                <li class="nav-item"><a href="{%url 'admin:index' %}" class="nav-link">Admin</a></li>
                <li class="nav-item"><a href="{% url 'logout' %}" class="nav-link">LOGOUT</a></li>
                
                {% else %}
                
                <li class="nav-item"><a href="{% url 'basic_app:user_login' %}" class="nav-link">Login</a></li>
                <li class="nav-item"><a href="{% url 'basic_app:register' %}" class="nav-link">Register</a></li>
                
                {% endif %}
                
            </ul>
        </div>

    </nav>

    <div class="container">
        <div class="jumbotron">
            
            {% block content %}
            
            {% endblock content %}
            
        </div>
    </div>
        
</body>
</html>

learning_users/templates/basic_app/index.html
{% extends "basic_app/base.html" %}


{% block content %}


{% if registered %}

    <h1>WElcome from Index</h1>

{% else %}


{% if user.is_authenticated %}
    
    <h6>dear {{request.user.username}},</h6>
    <h3>Welcome to Django!</h3>
    
    {% else %}
    
    <h3>
        Join our Community NOW!
    </h3>
        {% endif %}
    

{% endif %}

{% endblock content  %}

learning_users/templates/basic_app/login.html
{% extends "basic_app/base.html" %}


{% block content %}

<h1>Login Form</h1>
<form action="{% url 'basic_app:user_login' %}" method="POST">
    {% csrf_token %}
    <label for="username">Username :</label>
    <input type="text" name="username" placeholder="Username">
    <label for="password">Password :</label>
    <input type="password" name="password" placeholder="Password">

    <input type="submit" value="Login">
</form>

  
{% endblock content  %}

learning_users/templates/basic_app/registration.html
{% extends "basic_app/base.html" %}
{% load static %}

{% block content %}

<h1>WElcome from Registration</h1>

{% if registered %}
    <h3>Thank you for register.</h3>
    You Can Now Visit Our Page <a href="{% url 'index' %}">Click Here</a>
{% else %}
    <h1>Register Here!</h1>
    <h3>Fill out the form:</h3>

    <form action="" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ user_form.as_p }}
        {{ profile_form.as_p }}
        <input type="submit" value="Register">
    </form>
{% endif %}
    
  
{% endblock content  %}